### ISSUE TITLE
Can not move the mouse when open client

### ISSUE THREAD

**Issue by codingwatching** [awowogei/fmc#1]
Hi @awowogei 
I can run the server and client but when the "Bevy App" show, the mouse can not move, please help me
My machine is Apple MacBook Pro M1 Max
```
warning: `bevy_game` (bin "bevy_game") generated 33 warnings (run `cargo fix --bin "bevy_game"` to apply 23 suggestions)
    Finished release [optimized] target(s) in 0.31s
     Running `target/release/bevy_game`
2023-04-21T12:24:28.083780Z  INFO bevy_render::renderer: AdapterInfo { name: "Apple M1 Max", vendor: 0, device: 0, device_type: IntegratedGpu, driver: "", driver_info: "", backend: Metal }
2023-04-21T12:24:28.203822Z  INFO bevy_winit::system: Creating new window "Bevy App" (0v0)
```

**Comment by codingwatching** [comment]
Hi there
I can move now but I can not see the mouse pointer (Crosshair)

**Comment by awowogei** [comment]
https://github.com/awowogei/fmc/blob/master/client/src/ui/mod.rs#L20
You can uncomment this, and you will have a cursor, it's just a little square, not pretty. I disabled it for screenshots.

**Comment by codingwatching** [comment]
Thank you so much!

**Comment by awowogei** [comment]
@codingwatching I noticed this when testing on another computer, the cursor froze when on the main menu. Was this what happened? In which case how did you fix it?

**Comment by codingwatching** [comment]
Yeah! That is the problem when the first time I open the client
The problem still happens now, after we open the client, the mouse will get stuck with the window. I use cmd+tab to change focus on another program (To see the mouse again, then move to the play button), And then I switch back to the FMC client, then I press Enter, that does the trick

**Comment by awowogei** [comment]
Maybe it is fixed now. I don't have mac so can't test.

**Comment by codingwatching** [comment]
I confirm it is fixed in Mac
But maybe the light works not correctly.., can you check it?
<img width="965" alt="image" src="https://user-images.githubusercontent.com/85933804/236146719-a6c0ce4d-3e0c-46ce-abd6-da8e0f6210d9.png">

**Comment by awowogei** [comment]
Yes I'm trying to get shadows, it's not working yet. I will try to fix it soon.
